name: car_okay
description: Car washing reservation.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.6.3
  firebase_core: ^2.15.0
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_image_compress: ^2.0.3
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  google_maps_flutter: ^2.3.1
  google_sign_in: ^6.1.4
  graphic: ^2.2.0
  http: ^1.1.0
  image_picker: ^1.0.1
  intl: ^0.18.1
  month_picker_dialog: ^2.0.2
  month_year_picker: ^0.3.0+1
  page_transition: ^2.0.9
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/image/logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/image/app_background.png
    - assets/image/logo.jpg
    - assets/image/profile_placeholder.png
    - assets/image/car_placeholder.png
    - assets/image/map_selected.png
    - assets/image/map.png
    - assets/image/check.png
    - assets/image/review.png
    - assets/image/review_black.png
    - assets/image/promotion.png
    - assets/svg/dots.svg
    - assets/svg/map.svg
    - assets/svg/more.svg
    - assets/logo/google.png
    - assets/icon/icon_camera.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
