// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFLkyRM6L1_Xgx5wr4nilQ9wpdlTwC-vA',
    appId: '1:1042195251774:web:e30ba1bd448cad08ae876f',
    messagingSenderId: '1042195251774',
    projectId: 'carokay-3a57e',
    authDomain: 'carokay-3a57e.firebaseapp.com',
    databaseURL: 'https://carokay-3a57e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carokay-3a57e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF73SdKv4zx7Fh04VVAr3_r46GB3LSVoM',
    appId: '1:1042195251774:android:77dea18dfd354b99ae876f',
    messagingSenderId: '1042195251774',
    projectId: 'carokay-3a57e',
    databaseURL: 'https://carokay-3a57e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carokay-3a57e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj43Yw_vTterjQQDEAfkpc9sTyRyKclUI',
    appId: '1:1042195251774:ios:f0bc7c493cca67bdae876f',
    messagingSenderId: '1042195251774',
    projectId: 'carokay-3a57e',
    databaseURL: 'https://carokay-3a57e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carokay-3a57e.appspot.com',
    androidClientId: '1042195251774-gu4bc6lqeau3frsb2jpn7jj525ve5566.apps.googleusercontent.com',
    iosClientId: '1042195251774-crkrg9jmonie1kj4e0u5ealk390eef3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.carOkay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj43Yw_vTterjQQDEAfkpc9sTyRyKclUI',
    appId: '1:1042195251774:ios:f3329e14ff0d2b2fae876f',
    messagingSenderId: '1042195251774',
    projectId: 'carokay-3a57e',
    databaseURL: 'https://carokay-3a57e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carokay-3a57e.appspot.com',
    androidClientId: '1042195251774-gu4bc6lqeau3frsb2jpn7jj525ve5566.apps.googleusercontent.com',
    iosClientId: '1042195251774-sp9hqqgc8gc4gad2h1srjakvjvv7afli.apps.googleusercontent.com',
    iosBundleId: 'com.example.carOkay.RunnerTests',
  );
}
